"""End-to-end CLI tests over the synthetic capture.

No real network traffic is involved; the capture is generated by Scapy in a
fixture. ``--filter`` is only exercised when libpcap/Npcap is available.
"""
from __future__ import annotations

import json
from typing import Any

import pytest

from pcap_insight.cli import main


def run_cli(*argv: str) -> tuple[int, str]:
    """Run main() capturing stdout+stderr, converting sys.exit to a code."""
    import contextlib
    import io

    stdout = io.StringIO()
    stderr = io.StringIO()
    exit_code = 0
    with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
        try:
            exit_code = main(list(argv))
        except SystemExit as exc:  # argparse errors call sys.exit()
            exit_code = int(exc.code or 0)
    return exit_code, stdout.getvalue() + stderr.getvalue()


class TestCliTables:
    def test_tables_output_all_sections(self, capture_path: str) -> None:
        code, out = run_cli(capture_path)
        assert code == 0
        for section in (
            "Summary",
            "Protocol breakdown",
            "Top talkers by packet count",
            "Top talkers by byte volume",
            "Top destination ports",
            "Suspicious patterns (heuristics, not ground truth)",
            "plaintext-credentials",
            "syn-scan",
            "dns-tunneling-candidate",
            "arp-spoofing-candidate",
        ):
            assert section in out, f"missing section: {section}"

    def test_talker_tables_show_org_columns(self, capture_path: str) -> None:
        """Enrichment is on by default, so the Org columns are populated."""
        code, out = run_cli(capture_path)
        assert code == 0
        # The synthetic capture is all RFC1918 + one public IP, so the org
        # column must show at least "Private" somewhere.
        assert "Source Org" in out
        assert "Dest Org" in out
        assert "Private" in out

    def test_missing_file_errors(self) -> None:
        code, out = run_cli("does-not-exist.pcap")
        assert code == 2
        assert "not found" in out.lower()


class TestCliJson:
    def test_json_export_structure(self, capture_path: str, capsys: pytest.CaptureFixture) -> None:
        code = main([capture_path, "--export", "json"])
        assert code == 0
        captured = capsys.readouterr()
        data: dict[str, Any] = json.loads(captured.out)
        assert set(data.keys()) == {
            "summary",
            "protocols",
            "top_talkers_by_packets",
            "top_talkers_by_bytes",
            "top_ports",
            "suspicious_findings",
        }
        assert data["summary"]["total_packets"] == 27
        assert len(data["suspicious_findings"]) >= 4
        types = {f["type"] for f in data["suspicious_findings"]}
        assert "plaintext-credentials" in types

        # Every talker row carries the org/ASN annotation fields.
        for row in data["top_talkers_by_packets"] + data["top_talkers_by_bytes"]:
            assert set(row) >= {"src", "dst", "src_org", "dst_org"}

    def test_summary_time_fields_consistent(self, capture_path: str, capsys: pytest.CaptureFixture) -> None:
        code = main([capture_path, "--export", "json"])
        assert code == 0
        captured = capsys.readouterr()
        data = json.loads(captured.out)
        summary = data["summary"]

        # Epoch seconds are present, in seconds, and end - start == duration.
        assert summary["start_time"] is not None
        assert summary["end_time"] is not None
        assert summary["start_time"] < summary["end_time"]
        assert abs(
            (summary["end_time"] - summary["start_time"]) - summary["duration_seconds"]
        ) < 1e-6

        # Readable UTC labels are provided and agree with the epoch values.
        utc = summary["start_time_utc"]
        assert isinstance(utc, str) and utc.endswith("+00:00")
        assert summary["end_time_utc"].endswith("+00:00")

    def test_json_export_with_filter(self, capture_path: str, capsys: pytest.CaptureFixture) -> None:
        try:
            code = main([capture_path, "--filter", "tcp", "--export", "json"])
        except SystemExit as exc:
            # Filtering unavailable on this platform (no libpcap/Npcap).
            if exc.code == 2:
                pytest.skip("BPF filtering unavailable (no libpcap/Npcap)")
            raise
        assert code == 0
        captured = capsys.readouterr()
        data: dict[str, Any] = json.loads(captured.out)
        assert data["summary"]["total_packets"] < 27
        by_proto = {p["protocol"]: p["count"] for p in data["protocols"]}
        assert by_proto.get("UDP", 0) == 0


class TestCliEnrichment:
    def test_enrichment_on_by_default_marks_private_ips(
        self, capture_path: str, capsys: pytest.CaptureFixture
    ) -> None:
        """Without --no-enrich the org annotations are populated (Private locally)."""
        code = main([capture_path, "--export", "json"])
        assert code == 0
        data: dict[str, Any] = json.loads(capsys.readouterr().out)

        all_rows = data["top_talkers_by_packets"] + data["top_talkers_by_bytes"]
        assert all_rows
        for row in all_rows:
            assert isinstance(row["src_org"], str)
            assert isinstance(row["dst_org"], str)
        # Every talker in the synthetic capture involves at least one RFC1918
        # host, which must be labeled "Private" without touching a database.
        rows_with_private_src = [r for r in all_rows if r["src"].startswith("10.")]
        assert rows_with_private_src
        assert all(r["src_org"] == "Private" for r in rows_with_private_src)

    def test_no_enrich_leaves_org_fields_null(
        self, capture_path: str, capsys: pytest.CaptureFixture
    ) -> None:
        """--no-enrich disables the lookup entirely; fields are null in JSON."""
        code = main([capture_path, "--no-enrich", "--export", "json"])
        assert code == 0
        data: dict[str, Any] = json.loads(capsys.readouterr().out)

        all_rows = data["top_talkers_by_packets"] + data["top_talkers_by_bytes"]
        assert all_rows
        assert all(r["src_org"] is None and r["dst_org"] is None for r in all_rows)

    def test_missing_geoip_db_emits_stderr_warning(
        self, capture_path: str, capsys: pytest.CaptureFixture, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Without a GeoLite2-ASN database the CLI warns (instead of silently 'Unknown')."""
        import pcap_insight.enrichment as enrichment

        # Force the "database not found" backend state.
        monkeypatch.setattr(enrichment, "_default_db_paths", lambda: [])
        enrichment._reader = None
        enrichment._reader_error = None

        code = main([capture_path, "--export", "json"])
        assert code == 0
        captured = capsys.readouterr()

        assert "warning: enrichment enabled but GeoLite2-ASN" in captured.err
        assert "--no-enrich" in captured.err
        # Public IPs resolve to "Unknown" without a database (not an error).
        data = json.loads(captured.out)
        assert data["summary"]["total_packets"] > 0

    def test_no_enrich_silences_stderr_warning(
        self, capture_path: str, capsys: pytest.CaptureFixture, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """--no-enrich skips the backend check entirely, so no warning is emitted."""
        import pcap_insight.enrichment as enrichment

        monkeypatch.setattr(enrichment, "_default_db_paths", lambda: [])
        enrichment._reader = None
        enrichment._reader_error = None

        code = main([capture_path, "--no-enrich", "--export", "json"])
        assert code == 0
        captured = capsys.readouterr()

        assert "warning: enrichment enabled" not in captured.err
        data = json.loads(captured.out)
        assert data["summary"]["total_packets"] > 0


class TestCliDemo:
    def test_demo_runs_and_creates_capture(
        self,
        tmp_path: pytest.TempPathFactory,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture,
    ) -> None:
        monkeypatch.chdir(tmp_path)
        code = main(["--demo", "--export", "json"])
        assert code == 0
        assert (tmp_path / "demo.pcap").exists()
        captured = capsys.readouterr()
        data: dict[str, Any] = json.loads(captured.out)
        assert data["summary"]["total_packets"] == 27

    def test_demo_conflicts_with_capture_argument(self) -> None:
        code, out = run_cli("somefile.pcap", "--demo")
        assert code == 2
        assert "cannot be combined" in out