"""End-to-end CLI tests over the synthetic capture.

No real network traffic is involved; the capture is generated by Scapy in a
fixture. ``--filter`` is only exercised when libpcap/Npcap is available.
"""
from __future__ import annotations

import json
from typing import Any

import pytest

from pcap_insight.cli import main


def run_cli(*argv: str) -> tuple[int, str]:
    """Run main() capturing stdout+stderr, converting sys.exit to a code."""
    import io
    import contextlib

    stdout = io.StringIO()
    stderr = io.StringIO()
    exit_code = 0
    with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
        try:
            exit_code = main(list(argv))
        except SystemExit as exc:  # argparse errors call sys.exit()
            exit_code = int(exc.code or 0)
    return exit_code, stdout.getvalue() + stderr.getvalue()


class TestCliTables:
    def test_tables_output_all_sections(self, capture_path: str) -> None:
        code, out = run_cli(capture_path)
        assert code == 0
        for section in (
            "Summary",
            "Protocol breakdown",
            "Top talkers by packet count",
            "Top talkers by byte volume",
            "Top destination ports",
            "Suspicious patterns (heuristics, not ground truth)",
            "plaintext-credentials",
            "syn-scan",
            "dns-tunneling-candidate",
            "arp-spoofing-candidate",
        ):
            assert section in out, f"missing section: {section}"

    def test_missing_file_errors(self) -> None:
        code, out = run_cli("does-not-exist.pcap")
        assert code == 2
        assert "not found" in out.lower()


class TestCliJson:
    def test_json_export_structure(self, capture_path: str, capsys: pytest.CaptureFixture) -> None:
        code = main([capture_path, "--export", "json"])
        assert code == 0
        captured = capsys.readouterr()
        data: dict[str, Any] = json.loads(captured.out)
        assert set(data.keys()) == {
            "summary",
            "protocols",
            "top_talkers_by_packets",
            "top_talkers_by_bytes",
            "top_ports",
            "suspicious_findings",
        }
        assert data["summary"]["total_packets"] == 27
        assert len(data["suspicious_findings"]) >= 4
        types = {f["type"] for f in data["suspicious_findings"]}
        assert "plaintext-credentials" in types

    def test_summary_time_fields_consistent(self, capture_path: str, capsys: pytest.CaptureFixture) -> None:
        code = main([capture_path, "--export", "json"])
        assert code == 0
        captured = capsys.readouterr()
        data = json.loads(captured.out)
        summary = data["summary"]

        # Epoch seconds are present, in seconds, and end - start == duration.
        assert summary["start_time"] is not None
        assert summary["end_time"] is not None
        assert summary["start_time"] < summary["end_time"]
        assert abs(
            (summary["end_time"] - summary["start_time"]) - summary["duration_seconds"]
        ) < 1e-6

        # Readable UTC labels are provided and agree with the epoch values.
        utc = summary["start_time_utc"]
        assert isinstance(utc, str) and utc.endswith("+00:00")
        assert summary["end_time_utc"].endswith("+00:00")

    def test_json_export_with_filter(self, capture_path: str, capsys: pytest.CaptureFixture) -> None:
        try:
            code = main([capture_path, "--filter", "tcp", "--export", "json"])
        except SystemExit as exc:
            # Filtering unavailable on this platform (no libpcap/Npcap).
            if exc.code == 2:
                pytest.skip("BPF filtering unavailable (no libpcap/Npcap)")
            raise
        assert code == 0
        captured = capsys.readouterr()
        data: dict[str, Any] = json.loads(captured.out)
        assert data["summary"]["total_packets"] < 27
        by_proto = {p["protocol"]: p["count"] for p in data["protocols"]}
        assert by_proto.get("UDP", 0) == 0


class TestCliDemo:
    def test_demo_runs_and_creates_capture(
        self,
        tmp_path: pytest.TempPathFactory,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture,
    ) -> None:
        monkeypatch.chdir(tmp_path)
        code = main(["--demo", "--export", "json"])
        assert code == 0
        assert (tmp_path / "demo.pcap").exists()
        captured = capsys.readouterr()
        data: dict[str, Any] = json.loads(captured.out)
        assert data["summary"]["total_packets"] == 27

    def test_demo_conflicts_with_capture_argument(self) -> None:
        code, out = run_cli("somefile.pcap", "--demo")
        assert code == 2
        assert "cannot be combined" in out